const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('electronAPI', {
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  getGitStatus: (folderPath) => ipcRenderer.invoke('get-git-status', folderPath),
  getBranches: (folderPath) => ipcRenderer.invoke('get-branches', folderPath),
  getCommits: (folderPath, branch) => ipcRenderer.invoke('get-commits', folderPath, branch),
  createBranch: (folderPath, branch) => ipcRenderer.invoke('create-branch', folderPath, branch),
  checkoutBranch: (folderPath, branch) => ipcRenderer.invoke('checkout-branch', folderPath, branch),
  commitChanges: (folderPath, files, message) => ipcRenderer.invoke('commit-changes', folderPath, files, message),
  deleteBranch: (folderPath, branch, deleteRemote) => ipcRenderer.invoke('delete-branch', folderPath, branch, deleteRemote),
  pushChanges: (folderPath, branchName) => ipcRenderer.invoke('push-changes', folderPath, branchName),
  packageApp: () => ipcRenderer.invoke('package-app'),
  pullChanges: (folderPath) => ipcRenderer.invoke('pull-changes', folderPath),
  checkUnpushedCommits: (folderPath) => ipcRenderer.invoke('check-unpushed-commits', folderPath),
  getMergeStatus: (folderPath) => ipcRenderer.invoke('get-merge-status', folderPath),
  getRemoteUrl: (folderPath) => ipcRenderer.invoke('get-remote-url', folderPath),
  gitDiffBranches: (folderPath, branch1, branch2) => ipcRenderer.invoke('git-diff-branches', folderPath, branch1, branch2),
  gitMerge: (folderPath, fromBranch) => ipcRenderer.invoke('git-merge', folderPath, fromBranch),
  gitAbortMerge: (folderPath) => ipcRenderer.invoke('git-abort-merge', folderPath),
  readFileContent: (folderPath, filePath) => ipcRenderer.invoke('read-file-content', folderPath, filePath),
  writeFileContent: (folderPath, filePath, content) => ipcRenderer.invoke('write-file-content', folderPath, filePath, content),
  gitStageFile: (folderPath, filePath) => ipcRenderer.invoke('git-stage-file', folderPath, filePath),
  gitCommitMerge: (folderPath, message) => ipcRenderer.invoke('git-commit-merge', folderPath, message),
  gitClone: (url, parentFolder, repoName) => ipcRenderer.invoke('git-clone', url, parentFolder, repoName),
  openExternalUrl: (url) => ipcRenderer.invoke('open-external-url', url),
  // ── Advanced Git Operations ──────────────────────────────────────────────
  gitStash: (folderPath, message) => ipcRenderer.invoke('git-stash', folderPath, message),
  gitStashList: (folderPath) => ipcRenderer.invoke('git-stash-list', folderPath),
  gitStashApply: (folderPath, index) => ipcRenderer.invoke('git-stash-apply', folderPath, index),
  gitStashPop: (folderPath, index) => ipcRenderer.invoke('git-stash-pop', folderPath, index),
  gitStashDrop: (folderPath, index) => ipcRenderer.invoke('git-stash-drop', folderPath, index),
  gitCherryPick: (folderPath, commitId, targetBranch) => ipcRenderer.invoke('git-cherry-pick', folderPath, commitId, targetBranch),
  gitRevert: (folderPath, commitId) => ipcRenderer.invoke('git-revert', folderPath, commitId),
  gitListTags: (folderPath) => ipcRenderer.invoke('git-list-tags', folderPath),
  gitListPublishedTags: (folderPath) => ipcRenderer.invoke('git-list-published-tags', folderPath),
  gitCreateTag: (folderPath, name, message) => ipcRenderer.invoke('git-create-tag', folderPath, name, message),
  gitDeleteTag: (folderPath, name) => ipcRenderer.invoke('git-delete-tag', folderPath, name),
  gitPushTag: (folderPath, name) => ipcRenderer.invoke('git-push-tag', folderPath, name),
  gitInteractiveRebase: (folderPath, baseCommit, todoList) => ipcRenderer.invoke('git-interactive-rebase', folderPath, baseCommit, todoList),
  gitRebaseContinue: (folderPath) => ipcRenderer.invoke('git-rebase-continue', folderPath),
  gitRebaseAbort: (folderPath) => ipcRenderer.invoke('git-rebase-abort', folderPath),
  // Submodules
  gitGetSubmodules: (folderPath) => ipcRenderer.invoke('git-get-submodules', folderPath),
  gitAddSubmodule: (folderPath, repoUrl, subPath) => ipcRenderer.invoke('git-add-submodule', folderPath, repoUrl, subPath),
  gitUpdateSubmodule: (folderPath, subPath) => ipcRenderer.invoke('git-update-submodule', folderPath, subPath),
  gitRemoveSubmodule: (folderPath, subPath) => ipcRenderer.invoke('git-remove-submodule', folderPath, subPath),
  // Diff commits
  gitDiffCommits: (folderPath, commitA, commitB) => ipcRenderer.invoke('git-diff-commits', folderPath, commitA, commitB),
  // Multirepo
  gitGetRepoInfo: (folderPath) => ipcRenderer.invoke('git-get-repo-info', folderPath),
  gitPullRepo: (folderPath) => ipcRenderer.invoke('git-pull-repo', folderPath),
  gitPushRepo: (folderPath) => ipcRenderer.invoke('git-push-repo', folderPath),
})
